server:
  port: 8080
  
management:
  context-path: "/actuator"
  
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE:http://localhost:8761/eureka/}

spring:
  boot:
    admin:
      username: "${security.user.name}"       #These two are needed so that the client
      password: "${security.user.password}"   #can register at the protected server api
      client:
        metadata:
          user.name: "${security.user.name}"          #These two are needed so that the server
          user.password: "${security.user.password}" #can access the proteceted client endpoints


security:
  user:
    name: ${security.user.name:admin}
    password: ${security.user.password:admin}