server:
  port: 8080

security: 
  user: 
    name: parag
    password: parag
      
spring:
  boot:
    admin:
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream,activiti

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE:http://parag:parag@localhost:8761/eureka/}
