server:
  port: ${PORT:8761}
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
spring: 
  boot:
    admin:
      url: ${ADMIN_SERVICE:http://localhost:8080}
      username: ${ADMIN_USERNAME:admin}
      password: ${ADMIN_PASSWORD:admin}