server:
  port: 8080
  
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE:http://localhost:8761/eureka/}
      
spring:
  boot:
    admin:
      url: ${ADMIN_SERVICE:http://localhost:8080}
      
management:
  security:
    enabled: false