server:
  port: 8080
  
security: 
  user: 
    name: parag
    password: parag
  
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE:http://parag:parag@localhost:8761/eureka/}
      
spring:
  oauth2:
    client:
      access-token-uri: http://parag:parag@localhost:9999/uaa/oauth/token
      user-authorization-uri: http://parag:parag@localhost:9999/uaa/oauth/authorize
      client-id: gateway-service
      client-secret: gateway-service  
