eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE:http://localhost:8761/eureka/}
      
spring:
  boot:
    admin:
      url: ${ADMIN_SERVICE:http://localhost:8080}
      
management:
  port: 9085
  context-path: "/actuator"  
  security:
    enabled: false