server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE:http://localhost:8761/eureka/}
      
spring:
  boot:
    admin:
      url: ${ADMIN_SERVICE:http://localhost:8080}
      client:
        metadata:
          user.name: ${security.user.name:admin}
          user.password: ${security.user.password:admin}